### ISSUE TITLE
Bug Report: <TypeError: object of type 'Definition' has no len()>

### ISSUE THREAD

**Issue by AllenSun1024** [vitsalis/PyCG#17]
Hello, there is a bug in your code, I'm looking forward that you can fix it as soon as possible. The detailed information is listed as below:

**1. Bug Description:**

`<TypeError: object of type 'Definition' has no len()>`  occurred when I was using PyCG to resolve tensorflow library code. 

Other important information in the bug report may include:

>   File "/home/allen/anaconda3/envs/python3.9/lib/python3.9/site-packages/pycg/processing/base.py", line 187, in do_assign
      if pos < len(decoded):

**2. Root Cause:**

I installed pycg-0.0.4 after running command "pip install pycg" as your README.md suggested. However, in [pycg/processing/base.py, line 184~185](https://github.com/vitsalis/PyCG/blob/ef121c7ffb5ee06f4952fbe209b326bb7bf12647/pycg/processing/base.py#L185), your code written in github is `if not isinstance(decoded, Definition) and pos < len(decoded): ` while the code in my local host after installation is `if pos < len(decoded): `, which triggered the bug.

**3. Possible Solution:**

Release the latest version to python.

Thanks!

**Comment by vitsalis** [comment]
Hello @QingYiSun, I will take a look at that as soon as time allows. Thanks!
