### ISSUE TITLE
Panda or Pytorch cannot be detected

### ISSUE THREAD

**Issue by YZ-eng** [vitsalis/PyCG#2]
I cannot use PYCG to detect Pandas or PyTorch, it seems that it takes so long that I quit the program

**Comment by vitsalis** [comment]
I have added the `--max-iter` command-line argument that specifies that the maximum number of passes of the fix-point iteration algorithm. Maybe setting this to a low number can help.

**Comment by QingYiSun** [comment]
Hi, Have you fixed your problem? @YZ-eng
