### ISSUE TITLE
functions call stack with random order?

### ISSUE THREAD

**Issue by theweaklink** [vitsalis/PyCG#33]
Hello,

very nice tool with plentry of potential IMHO!

I was just wondering whether the order of the function call could be preserved?

For instance for a function I would get the following:
```
   "flow.runner.run":[
      "<builtin>.len",
      "<builtin>.print",
      "flow.display.plot",
      "pandas.read_csv",
      "numpy.arange",
      "pandas.DataFrame"
   ],
```

the order of the functions called in the array is not the same order as the original python file. Also if I run `pycg` several times in a row, I would get a different order each time. 

Would it be possible to keep the actual call order? That would definitely be valuable to ensure the sequence of functions being called.
Thanks for your insight.

**Comment by vitsalis** [comment]
The current implementation is heavily reliant on sets for efficient inclusion checks. That's why the order seems to be different on different executions. However, it is possible that the order of the functions can be preserved after a refactoring.

**Comment by theweaklink** [comment]
Sorry to be late on that reply. Indeed that would require some refactoring with a certain potential for breaking things.
I intuitively thought this could be interesting for sequence graph analysis. 
I'll close this issue, thanks.
