### ISSUE TITLE
What tool have you used to generate the figures from JSON/FASTEN?

### ISSUE THREAD

**Issue by davide-q** [vitsalis/PyCG#41]
The paper contains some figures with arrows and colors, very useful for human (rather than machine) understanding.

However it looks like this project generates output in either JSON or FASTEN format which are machine-friendly but not human friendly and certainly not graphics. How have you generated the figures in the paper and/or what would you recommend people to use to go from JSON (or FASTEN) to an output more suitable for human consumption?

**Comment by vitsalis** [comment]
The figures were created manually using the [DOT language](https://graphviz.org/doc/info/lang.html). Unfortunately, while I looked for it when writing the paper, I did not find a tool that can efficiently convert JSON to a visual representation.
