### ISSUE TITLE
Can PyCG optimize to flow sensitive?

### ISSUE THREAD

**Issue by Peteling** [vitsalis/PyCG#46]
Sometimes the PyCG can not get right callgraph because it is flow in-sensitive, there is a example
```
def nested_func():
    pass


def nested_func2():
    pass


def param_func(b):
    b()


def func(a):
    a(nested_func)


def func2(a):
    a(nested_func2)


var_b = func
var_c = func2

var_b = var_c
var_a = var_b

var_a(param_func)
```
will get the wrong callgraph because the 
```
{
  "micro-benchmark.snippets.test": [
    "micro-benchmark.snippets.test.func",
    "micro-benchmark.snippets.test.func2"
  ],
  "micro-benchmark.snippets.test.nested_func": [],
  "micro-benchmark.snippets.test.nested_func2": [],
  "micro-benchmark.snippets.test.param_func": [
    "micro-benchmark.snippets.test.nested_func2",
    "micro-benchmark.snippets.test.nested_func"
  ],
  "micro-benchmark.snippets.test.func": [
    "micro-benchmark.snippets.test.param_func"
  ],
  "micro-benchmark.snippets.test.func2": [
    "micro-benchmark.snippets.test.param_func"
  ]
}
```
I think it is not easy to optimizate, I want to know if it can be optimizated like these cases?

**Comment by ashwinprasadme** [comment]
I have made flow-sensitivity improvements in my extension of PyCG for the [HeaderGen](https://github.com/ashwinprasadme/headergen) project. I would like to incorporate these changes into the main PyCG implementation moving forward. However, I believe it would be beneficial to discuss the design decisions and make it even more robust. I'm open to having a discussion with @vitsalis and @gdrosos to explore these ideas further.

**Comment by vitsalis** [comment]
How do you solve the above issue in the extension?

**Comment by ashwinprasadme** [comment]
I have incorporated Def-use chains generated by [Beniget](https://github.com/serge-sans-paille/beniget) to reason about variable definitions and their uses.

call graph generated by [HeaderGen](https://github.com/ashwinprasadme/headergen) looks like this:
```json
{
    "main": [
        "main.func2:17"
    ],
    "main.nested_func:1": [],
    "main.nested_func2:5": [],
    "main.param_func:9": [
        "main.nested_func2:5"
    ],
    "main.func:13": [],
    "main.func2:17": [
        "main.param_func:9"
    ]
}
``` 

The difference in the assignment graph looks like this for `var_a`, `var_b`, `var_c`:

### PyCG
```json
"main.var_b": [
    "main.var_c",
    "main.func"
],
"main.var_c": [
    "main.func2"
],
"main.var_a": [
    "main.var_b"
]
```

### [HeaderGen](https://github.com/ashwinprasadme/headergen)
```json
"main.var_b:21": [
    "main.func:13"
],
"main.var_c:22": [
    "main.func2:17"
],
"main.var_b:24": [
    "main.var_c:22"
],
"main.var_a:25": [
    "main.var_b:24"
]
```

**Comment by vitsalis** [comment]
Closing due to archival of repository.
