### ISSUE TITLE
how to analyse cg of __init__.py

### ISSUE THREAD

**Issue by doublebubble626** [vitsalis/PyCG#52]
It seems that PyCG will skip this files

**Comment by seanxiaoyan** [comment]
In my experience with PYCG, I think pycg analyzes __init__.py, just that the "__init__" is not included in the name of the method in the resulted call graph.

E.g., you have a package named "a" and a method in "a/__init__.py" named as "foo". Then in the call graph you will see the method name is "a.foo".

You might want to double check this?

**Comment by vitsalis** [comment]
Yep, @seanxiaoyan notes exactly what happens.
