### ISSUE TITLE
analysis does not follow explicit super()-calls

### ISSUE THREAD

**Issue by julian-goettingen** [vitsalis/PyCG#64]
I have noticed that pycg does not follow methods called on super()  (A).
pycg does follow method-calls on other objects (B), and it follows implicit calls to super (C) (when calling a method on self that is only defined on the superclass)

example of (A), (B), (C) in a file called `mod.py`

```
class Sup:

    def __init__(self):
        self.init_me()
    
    def init_me(self):
        pass
    
    def super_func(self):
        pass

class D:
    def __init__(self):
        pass
    
    def d_method(self):
        pass


class C(Sup):

    def __init__(self, a):
        super().__init__() # (A)
        self.init_C()
        D().d_method() # (B)
        self.super_func() # (C)

    def init_C(self):
        pass

    def unused(self):
        pass

```
The output of `pycg mod.py` is:
`{"mod": [], "mod.Sup.__init__": ["mod.Sup.init_me"], "mod.Sup.init_me": [], "mod.Sup.super_func": [], "mod.D.__init__": [], "mod.D.d_method": [], "mod.C.__init__": ["mod.D.d_method", "mod.D.__init__", "mod.C.init_C", "<builtin>.super", "mod.Sup.super_func"], "<builtin>.super": [], "mod.C.init_C": [], "mod.C.unused": []}`

So the tool correctly identifies `C.__init__` as calling `d_method` from class D and `super_func` from the super-class, but not `Sup.__init__`, which is surprising to me.

**Comment by jacksongoode** [comment]
This is interesting... Our team might also be concerned about this since we use composable classes that often call super.

**Comment by vitsalis** [comment]
Closing due to archival of repository.
