### ISSUE TITLE
Ignore built-in functions, numpy, torch...

### ISSUE THREAD

**Issue by ahallin** [vitsalis/PyCG#69]
I have a pretty complex code and I am only interested in how the functions defined in that code relate to each other. I am not interested in seeing all calls to numpy and pytorch, for example. Excluding these would likely speed up the execution as well. Is there a way to exclude these?

**Comment by jacksongoode** [comment]
This would be a nice optional inclusion!

**Comment by vitsalis** [comment]
Closing due to archival of repository.
