### ISSUE TITLE
Handling posonlyargs

### ISSUE THREAD

**Issue by yusiyoh** [vitsalis/PyCG#72]
I am working on a complex python project and encountered an issue. As also mentioned here: https://stackoverflow.com/questions/59564990/typeerror-required-field-posonlyargs-missing-from-arguments-error-running-a-p , ast reads posonlyargs after python 3.8 and it is not handled here:
https://github.com/vitsalis/PyCG/blob/014d21cb4bc807682ad0527e4b2c2f732fb62bc4/pycg/processing/preprocessor.py#L51

While I am not sure, adding another condition that checks node.args.args seems to make it work since it will not fail at https://github.com/vitsalis/PyCG/blob/014d21cb4bc807682ad0527e4b2c2f732fb62bc4/pycg/processing/preprocessor.py#L59
Otherwise, node.args.args becomes 0 and for loop does not stop with: https://github.com/vitsalis/PyCG/blob/014d21cb4bc807682ad0527e4b2c2f732fb62bc4/pycg/processing/preprocessor.py#L55-L56

Instead, 
```
if not d or not node.args.args:
     continue
```
can resolve it.

I am using Python 3.11 on Windows 11

**Comment by jacksongoode** [comment]
I think this is handled by https://github.com/vitsalis/PyCG/pull/70 @vitsalis ?

**Comment by vitsalis** [comment]
Closing due to archival of repository.
